# Generated by Django 4.2.7 on 2024-03-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(blank=True, choices=[('6:00 AM', '6:00 AM'), ('12:00 PM', '12:00 PM'), ('3:00 PM', '3:00 PM'), ('8:00 PM', '8:00 PM')], max_length=15, null=True)),
                ('seat', models.CharField(blank=True, choices=[('AC', 'AC'), ('NON-AC', 'NON-AC')], max_length=15, null=True)),
                ('seat_number', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('A4', 'A4'), ('A5', 'A5')], max_length=5, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('destination', models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Sunamganj', 'Sunamganj'), ('Dhaka', 'Dhaka'), ('Chittagong', 'Chittagong')], max_length=200, null=True)),
                ('station', models.ManyToManyField(to='train.station')),
            ],
        ),
    ]
