# Generated by Django 4.2.7 on 2024-04-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_seat_formation_borrowedticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_list',
            name='destination',
            field=models.CharField(blank=True, choices=[('Sylhet', 'Sylhet'), ('Kamlapur', 'Kamlapur'), ('BimanBandar', 'BimanBandar'), ('Chattagram', 'Chattagram'), ('CoxsBazar', 'CoxsBazar'), ('Tangail', 'Tangail'), ('Narshingdi', 'Narshingdi'), ('Rajshahi', 'Rajshahi'), ('Joydevpur', 'Joydevpur'), ('Sirajganj', 'Sirajganj')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='train_list',
            name='seat',
            field=models.CharField(blank=True, choices=[('AC', 'AC'), ('NON-AC', 'NON-AC'), ('Snighdha', 'Snighdha'), ('S_Chair', 'S_Chair')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='train_list',
            name='time',
            field=models.CharField(blank=True, choices=[('6:00 AM', '6:00 AM'), ('12:00 PM', '12:00 PM'), ('3:00 PM', '3:00 PM'), ('8:00 PM', '8:00 PM'), ('9:00 PM', '9:00 PM'), ('11:00 PM', '11:00 PM'), ('7:30 PM', '7:30 PM'), ('7:00 AM', '7:00 AM'), ('8:00 AM', '8:00 AM'), ('5:00 PM', '5:00 PM')], max_length=15, null=True),
        ),
    ]
